In [109]:
from pylab import *
from numpy import *
from sklearn import svm

In [110]:
dat = loadtxt('scale.txt')
n = len(dat); print(n)
X = zeros((4, n))
Y = zeros(n)
for i in range(n):
    Y[i] = dat[i,0]
    X[:,i] = dat[i,1:5]

625


In [111]:
XT = X.transpose()
XXT = matmul(X,XT)
XY = matmul(X,Y)
w = matmul(inv(XXT),XY)

In [112]:
print(w)

[-0.2792 -0.2792  0.2792  0.2792]


In [113]:
# 1. linear model
xi = ones(4)
accuracy = 0
tot_number = 0
for i in range(n):
    tot_number = tot_number + 1
    
    xi[:] = dat[i,1:5]
    yi = dat[i,0]
    
    yt = matmul(w,xi)
    if yt >0:
        predict = 1
    elif yt <0:
        predict = -1
    else:
        predict = 0
    if yi == predict:
        accuracy = accuracy + 1
        
Acc = accuracy/tot_number *100
print('Accuracy of linear model = ', Acc)

Accuracy of linear model =  87.2


In [114]:
# 2. gradient decent method
wn = w*0 + 0.1
lam = 0.00001
err = 10
while err >= 0.00005:
    grad = 0*X[:,0]
    wo = wn
    for i in range(400):
        grad = grad + (matmul(wo,X[:,i])-Y[i])*X[:,i]
    wn = wo - lam*grad
    err = sqrt(sum((wn-wo)**2))
print(wn)

[-0.30433943 -0.27496603  0.28627357  0.28627357]


In [115]:
xi = ones(4)
accuracy = 0
tot_number = 0
for i in range(n):
    tot_number = tot_number + 1
    
    xi[:] = dat[i,1:5]
    yi = dat[i,0]
    
    yt = matmul(wn,xi)
    if yt >0:
        predict = 1
    elif yt <0:
        predict = -1
    else:
        predict = 0
    if yi == predict:
        accuracy = accuracy + 1
        
Acc = accuracy/tot_number *100
print('Accuracy of gradient decent method = ', Acc)

Accuracy of gradient decent method =  88.96


In [116]:
# 3. stochastic gradient descent 
wn = w*0 +0.0
lam = 0.001
Epoch_num = 100
for epoch in range(Epoch_num):
    for i in range(n):
        grad = (matmul(wn,X[:,i])-Y[i])*X[:,i]
        wn = wn - lam * grad
print('Epoch num =========', epoch)
print(wn)

Epoch num ========= 99
[-0.29830546 -0.27264899  0.28053226  0.27651112]


In [117]:
xi = ones(4)
accuracy = 0
tot_number = 0
for i in range(n):
    tot_number = tot_number + 1
    
    xi[:] = dat[i,1:5]
    yi = dat[i,0]
    
    yt = matmul(wn,xi)
    if yt >0:
        predict = 1
    elif yt <0:
        predict = -1
    else:
        predict = 0
    if yi == predict:
        accuracy = accuracy + 1
        
Acc = accuracy/tot_number *100
print('Accuracy of stochastic gradient descent  = ', Acc)

Accuracy of stochastic gradient descent  =  88.48


In [118]:
# 4(1). SVM with linear kernel
clf = svm.SVC(kernel = 'linear')
clf.fit(transpose(X),Y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [119]:
xi = ones(4)
clf.predict([xi])[0]

0.0

In [120]:
xi = ones(4)
accuracy = 0
tot_number = 0
for i in range(n):
    tot_number = tot_number + 1
    
    xi[:] = dat[i,1:5]
    yi = dat[i,0]
    
    predict = clf.predict([xi])[0]
    
    if yi == predict:
        accuracy = accuracy + 1
        
Acc = accuracy/tot_number *100
print('Accuracy of SVM with linear  = ', Acc)

Accuracy of SVM with linear  =  91.67999999999999


In [121]:
# 4(2). SVM with rbf kernel
clf = svm.SVC(C = 3, kernel = 'rbf', gamma = 0.1)
clf.fit(transpose(X),Y)

SVC(C=3, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [122]:
xi = ones(4)
clf.predict([xi])[0]

0.0

In [123]:
xi = ones(4)
accuracy = 0
tot_number = 0
for i in range(n):
    tot_number = tot_number + 1
    
    xi[:] = dat[i,1:5]
    yi = dat[i,0]
    
    predict = clf.predict([xi])[0]
    
    if yi == predict:
        accuracy = accuracy + 1
        
Acc = accuracy/tot_number *100
print('Accuracy of SVM with rbf  = ', Acc)

Accuracy of SVM with rbf  =  98.08
